# Generated by Django 3.2.7 on 2021-09-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0006_alter_stock_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='item_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
