# Generated by Django 3.2.7 on 2021-09-12 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0008_auto_20210912_0438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='item_Buy_price',
            new_name='item_buy_price',
        ),
    ]
