# Generated by Django 3.2.7 on 2021-09-12 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0009_rename_item_buy_price_stock_item_buy_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='category',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='item_buy_price',
            new_name='Product_Buy_Price',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='item_id',
            new_name='Product_Code',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='item_name',
            new_name='Product_Name',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='item_seles_price',
            new_name='Product_Seles_Price',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='quantity',
            new_name='Quantity',
        ),
    ]
