# Generated by Django 3.2.7 on 2021-09-12 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0010_auto_20210912_0501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='reorder_level',
            new_name='Alert_Level',
        ),
    ]
