# Generated by Django 3.2.7 on 2021-09-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0011_rename_reorder_level_stock_alert_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='Customer_Address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='Customer_Email',
            field=models.EmailField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='Customer_Gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='Customer_Mobile',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='Customer_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='Opening_Balance',
            field=models.IntegerField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='Receipt_Type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='StockHistory',
        ),
    ]
