# Generated by Django 3.2.7 on 2021-09-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0012_auto_20210913_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Customer_Gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50, null=True)),
                ('Customer_Mobile', models.CharField(blank=True, max_length=40, null=True)),
                ('Customer_Address', models.CharField(blank=True, max_length=30, null=True)),
                ('Customer_Email', models.EmailField(blank=True, max_length=20, null=True)),
                ('Opening_Balance', models.IntegerField(blank=True, max_length=30, null=True)),
                ('Receipt_Type', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='stock',
            name='Customer_Address',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='Customer_Email',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='Customer_Gender',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='Customer_Mobile',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='Customer_Name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='Opening_Balance',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='Receipt_Type',
        ),
    ]
