# Generated by Django 3.2.7 on 2021-09-14 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0013_auto_20210913_0658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Opening_Balance',
            new_name='Customer_Due',
        ),
    ]
