# Generated by Django 3.2.7 on 2021-09-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0015_stock_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Customer_Due',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
