# Generated by Django 3.2.7 on 2021-09-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0017_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Due_amount',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
