# Generated by Django 3.2.7 on 2021-09-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0018_invoice_due_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
