# Generated by Django 3.2.7 on 2021-09-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0022_auto_20210915_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Net_amount',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
