# Generated by Django 3.2.7 on 2021-09-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0025_auto_20210917_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='Customer_Name',
            new_name='Name',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_elaven',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='line 11'),
        ),
    ]
