# Generated by Django 3.2.7 on 2021-09-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0026_auto_20210917_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='Name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
