# Generated by Django 3.2.7 on 2021-09-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0027_alter_invoice_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily_accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Payment_type', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Receipt', 'Receipt'), ('Cheque', 'cheque'), ('Balance Transfer', 'Balance Transfer')], default='', max_length=20, null=True)),
                ('Transcation_to', models.CharField(max_length=30, null=True)),
                ('Expense_reason', models.CharField(max_length=50, null=True)),
                ('Debit', models.IntegerField(blank=True, default='0', null=True)),
                ('Credit', models.IntegerField(default='0', null=True)),
                ('Balance', models.IntegerField(default='0', null=True)),
            ],
        ),
    ]
